### ISSUE TITLE
https://coderus.openrepos.net/ ⇒ 502 Bad Gateway

### ISSUE THREAD

**Issue by Olf0** [CODeRUS/django-test#11]
Trying to access https://coderus.openrepos.net/pm2/projects/ results in:

502 Bad Gateway
<sup>nginx/1.4.6 (Ubuntu)</sup>

Originally [reported by Objectifnul and adekker at FSO](https://forum.sailfishos.org/t/bugs-in-patchmanager-3-1-0/8552/6?u=olf) nine days ago.  I noticed this today and confirmed that it is still the case: All `https` accesses at `coderus.openrepos.net` fail with a `502 Bad Gateway` error and `http` is redirected to `https` (which is absolutely O.K.).  DNS, routing and `ping` do work fine, with `coderus.openrepos.net` being resolved to `static.10.21.201.138.clients.your-server.de (138.201.21.10)`.

@CODeRUS, can you please take a look at this infrastructure issue.  As long this persists, Patchmanager is mostly useless.

P.S.: Just to notify @nephros and @b100dian that I filed this issue here.

P.P.S.: And finally I read [@nephros' message at FSO](https://forum.sailfishos.org/t/patchmanager-web-catalog-failure-any-workaround/12842/21?u=olf) that a solution is "in the works".  Sorry for documenting this issue again, but that piece of information was not easy to find.

**Comment by CODeRUS** [comment]
hi, i have nothing to do with the issue :(
Basil is working on it, some server problems.

**Comment by b100dian** [comment]
Should be up now, based on the telegram messages (and my quick testing), thanks!
