### ISSUE TITLE
`https://coderus.openrepos.net/` is down

### ISSUE THREAD

**Issue by Olf0** [CODeRUS/django-test#19]
[`https://coderus.openrepos.net/`](https://coderus.openrepos.net/) results in a blank page (which is "normal"), and all its sub-pages in an error message:
**`502 Bad Gateway`**
`nginx/1.14.0 (Ubuntu)`

E.g. [`https://coderus.openrepos.net/pm2/`](https://coderus.openrepos.net/pm2/) or [`https://coderus.openrepos.net/whitesoft/sailversion`](https://coderus.openrepos.net/whitesoft/sailversion)

In contrast to that [`https://openrepos.net/`](https://openrepos.net/) and all its sub-pages are working well.

@CODeRUS, can you please contact Basil to resolve this issue.  If there is anything I can do to support you in this regard, please let me know.

**Comment by CODeRUS** [comment]
thanks for heads-up, fixed
